postgres-identity-general:
  host: '127.0.0.1'
  port: 5432
  passwordPath: 'secrets/pg_pass'
  username: 'postgres'
  database: 'blogs'

firebase:
  apiKey: '***'
  projectId: '***'

redis-identity-general:
  url: 'redis://0.0.0.0:6379'
